theme: jekyll-theme-chirpy
lang: en
timezone: Asia/Kolkata
title: Ashutosh Panda
tagline: I'm Batman
description: finding ashu
url: "https://zen-zap.github.io"
github:
  username: zen-zap
social:
  name: Ashutosh Panda
  email: zenzap34@gmail.com
  links:
    - https://github.com/zen-zap
    - https://discord.com/users/1128746304189780118
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:
analytics:
  google:
    id: G-3VN528Q133
  goatcounter:
    id: zen-zap
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:
pageviews:
  provider: goatcounter
theme_mode:
cdn: "/assets/img"
avatar: g3.png
social_preview_image:
toc: true
comments:
  provider: giscus
  giscus:
    repo: zen-zap/zen-zap.github.io
    repo_id: R_kgDOPJHl3g
    category: General
    category_id: DIC_kwDOPJHl3s4Cs3dm
    mapping: pathname
    input_position: bottom
    reactions_enabled: 1
    lang: en
assets:
  self_host:
    enabled:
    env:
search:
  enabled: true
  exclude: [ '/projects/**' ]   # if you don’t want to index projects
  engine: lunr
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:
pagination:
  enabled: true
  per_page: 10
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2
baseurl: ""
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
collections:
  tabs:
    output: true
    sort_by: order
  projects:
    output: true
    sort_by: date
    permalink: /projects/:path/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: true
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: ""
      type: projects
    values:
      layout: project
sass:
  style: compressed
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - assets/feed.xml
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

plugins:
  - jekyll-feed         # RSS feed for posts
  - jekyll-seo-tag      # SEO metadata tags
  - jekyll-sitemap      # sitemap.xml
  - jekyll-archives     # category/tag/archive pages
  - jekyll-paginate-v2  # advanced pagination
